export enum PostHogEventsName {
  PRESS_TO_NEXT_STEP = "PRESS_TO_NEXT_STEP",
  PRESS_TO_START_ONBOARDING = "PRESS_TO_START_ONBOARDING",
  PRESS_TO_AUTHENTICATE_ANONYMOUSLY = "PRESS_TO_AUTHENTICATE_ANONYMOUSLY",
  PRESS_TO_NAVIGATE_TO_START_SCREEN = "PRESS_TO_NAVIGATE_TO_START_SCREEN",
}
