export enum QueryKeys {
  GetFriends,
  GetProfile,
  GetMissions,
  GetChartData,
  GetAuthorInfo,
  GetProgressData,
  GetHistoricData,
  GetAchievements,
  GetUserLastSmoke,
  GetFriendRequests,
  GetUnreadMessagesCount,
  GetLatestSmokingRecord,
  GetConversationMessages,
  GetNotificationSettings,
  GetAllSmokingRecordsByMonth,
  GetMessagesFromPrivateConversation,
}
